### PR TITLE
Take first stab in CDF Code of Conduct

### PR DESCRIPTION
**Pull request by fdegir**
This document is adopted from CNCF Code of Conduct available below.

https://github.com/cncf/foundation/blob/main/code-of-conduct.md

### CODE REVIEW

**Review by justinabrahms — APPROVED** [review]

**Comment by fdegir** [comment]
It looks like code of conduct is documented in .github repository but it didn't come up when I searched within the cdfoundation organization.

https://github.com/cdfoundation/.github/blob/main/CODE_OF_CONDUCT.md

I'll replace the code of conduct documented by this PR with the one from .github repo linked above.

**Comment by zestyroxy** [comment]
+1

**Review by oleg-nenashev — COMMENTED** [review]
While we are here, I would strongly recommend updating the Contributor Covenant to the version 2.x. It is important for the foundation, because the Contributor Covenant 2.0 shifts its focus from a project perspective to the whole community and its venues. See https://github.com/EthicalSource/contributor_covenant/blob/release/changelog for the summary

**Comment by fdegir** [comment]
Thanks for highlighting this @oleg-nenashev and yes, we should definitely do that.

Added this as a topic to today's TOC meeting with your comment.

**Review by r2liquibase — APPROVED** [review]

**Pull request closed without merging**
